telegram_default: &telegram_default
  telegram:
    token: <%= ENV['telegram_bot_token'] %>
    username: <%= ENV['telegram_bot_username'] %>

development:
  <<: *telegram_default

production:
  <<: *telegram_default

